Repository thoth-station/jupyterlab-requirements, pull requests merged in 2020-11, with the labels that each got.

#3 Initial files
  .eslintignore
  .eslintrc.js
  .gitignore
  .prettierignore
  .prettierrc
  .thoth.yaml
  MANIFEST.in
  OWNERS
  OWNERS_ALIASES
  Pipfile
  Pipfile.lock
  README.md
  install.json
  jupyterlab-requirements/__init__.py
  jupyterlab-requirements/_version.py
  package.json
  pyproject.toml
  requirements.txt
  setup.py
  src/button.tsx
  src/index.ts
  src/panel.ts
  style/index.css
  template/__init__.py
  tsconfig.json
  yarn.lock
Labels: size/XXL

#4 Automatic update of dependency thamos from 1.3.0 to 1.3.1
  Pipfile.lock
Labels: approved, bot, size/L

#8 Automatic update of dependency jupyterlab from 3.0.0rc7 to 3.0.0rc9
  Pipfile.lock
Labels: approved, bot, size/L

#9 Automatic update of dependency pytest-mypy from 0.7.0 to 0.8.0
  Pipfile.lock
Labels: approved, bot, size/L

#11 Automatic update of dependency jupyterlab from 3.0.0rc9 to 3.0.0rc10
  Pipfile.lock
Labels: approved, bot, size/L

#12 Automatic update of dependency hypothesis from 5.41.2 to 5.41.3
  Pipfile.lock
Labels: approved, bot, size/L

#20 Add thoth python and thoth common in requirements
  .gitignore
  MANIFEST.in
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/XXL

#22 Update tsconfig and yarn
  tsconfig.json
  yarn.lock
Labels: approved, size/XXL

#23 Create jupyterlab compliant extension
  .gitignore
  .thoth.yaml
  jupyter-config/jupyter_notebook_config.d/jupyterlab_requirements.json
  jupyter-config/jupyter_server_config.d/jupyterlab_requirements.json
  package.json
  setup.py
Labels: approved, size/M

#24 Pre-commit happy
  .pre-commit-config.yaml
  .prettierignore
  jupyter-config/jupyter_notebook_config.d/jupyterlab_requirements.json
  jupyter-config/jupyter_server_config.d/jupyterlab_requirements.json
  requirements.txt
  setup.py
  tsconfig.json
  yarn.lock
Labels: approved, size/M

#25 Introduce server endpoints
  jupyterlab_requirements/__init__.py
  jupyterlab_requirements/_version.py
  jupyterlab_requirements/dependency_management/__init__.py
  jupyterlab_requirements/dependency_management/config.py
  jupyterlab_requirements/dependency_management/customized_kernel.py
  jupyterlab_requirements/dependency_management/dependencies.py
  jupyterlab_requirements/dependency_management/environment.py
  jupyterlab_requirements/dependency_management/thoth.py
Labels: approved, size/XL

#32 Add handlers
  src/handler.ts
  src/kernel.ts
  src/notebook.ts
  src/thoth.ts
Labels: approved, size/L

#36 Add interfaces for requirements and thoth
  src/types/requirements.ts
  src/types/thoth.ts
Labels: approved, size/L

#37 Use advise_using_config method
  Pipfile.lock
  jupyterlab_requirements/dependency_management/dependencies.py
  jupyterlab_requirements/dependency_management/thoth.py
Labels: approved, size/L

#38 Adjust handlers with thoth config
  src/kernel.ts
  src/thoth.ts
Labels: approved, size/XS
