Repository thoth-station/jupyterlab-requirements, pull requests merged in 2021-04, with the labels that each got.

#255 Fix paths to store dependencies and .thoth.yaml in container
  jupyterlab_requirements/dependency_management/common.py
  jupyterlab_requirements/dependency_management/dependencies_files_handler.py
  jupyterlab_requirements/dependency_management/thoth_config_handler.py
  src/components/dependencyManagementUI.tsx
  src/helpers.ts
Labels: approved, size/M

#257 Fix/python version
  jupyterlab_requirements/__init__.py
  jupyterlab_requirements/dependency_management/__init__.py
  jupyterlab_requirements/dependency_management/discover_handler.py
  package.json
  src/helpers.ts
  src/kernel.ts
  src/notebook.ts
Labels: approved, size/L

#260 fix requirements files missing from source build
  MANIFEST.in
Labels: approved, size/XS
