Repository thoth-station/jupyterlab-requirements, pull requests merged in 2021-07, with the labels that each got.

#326 Provide more info on errors to user
  jupyterlab_requirements/dependency_management/base.py
  jupyterlab_requirements/dependency_management/pipenv.py
  jupyterlab_requirements/dependency_management/thoth.py
  src/components/dependencyManagementUI.tsx
Labels: approved, size/M

#328 Allow user to use force
  jupyterlab_requirements/dependency_management/thoth.py
  src/components/dependencyManagementUI.tsx
  src/thoth.ts
Labels: approved, size/M

#333 Fix/check initial packages
  babel.config.js
  jest.config.js
  package.json
  requirements.txt
  src/common.ts
  src/helpers.ts
  tests/thoth.test.ts
  tsconfig.json
  yarn.lock
Labels: approved, size/XXL

#340 Add youtube link to v0.8.0
  README.md
Labels: approved, size/XS

#341 Introduce Horus: jupyterlab requirements CLI
  MANIFEST.in
  Pipfile
  Pipfile.lock
  README.md
  horus
  jupyterlab_requirements/__init__.py
  jupyterlab_requirements/cli.py
  jupyterlab_requirements/dependency_management/__init__.py
  jupyterlab_requirements/dependency_management/discover_handler.py
  jupyterlab_requirements/dependency_management/install_handler.py
  jupyterlab_requirements/dependency_management/kernel_handler.py
  jupyterlab_requirements/dependency_management/lib.py
  jupyterlab_requirements/dependency_management/pipenv.py
  jupyterlab_requirements/dependency_management/thoth.py
  jupyterlab_requirements/dependency_management/thoth_config_handler.py
  package.json
  requirements.txt
  setup.py
  src/components/dependencyManagementUI.tsx
Labels: approved, size/XXL

#349 Fix CLI during setup
  CHANGELOG.md
  jupyterlab_requirements/cli.py
  setup.py
Labels: approved, size/S

#353 Some improvements and fixes
  README.md
  jupyterlab_requirements/cli.py
  jupyterlab_requirements/dependency_management/kernel_handler.py
  jupyterlab_requirements/dependency_management/lib.py
  jupyterlab_requirements/dependency_management/thoth_config_handler.py
  package.json
Labels: approved, size/L

#359 use thoth-advise manager instead of update manager
  .thoth.yaml
Labels: approved, size/XS

#360 Add link to v0.9.2 video
  README.md
Labels: approved, size/XS
