Repository thoth-station/jupyterlab-requirements, pull requests merged in 2021-11, with the labels that each got.

#561 Fix CSS table reformatting pandas dataframe output
  style/index.css
Labels: approved, size/XS

#562 Fix README to make twine happy
  README.rst
Labels: approved, size/XS

#560 Fix/horus-check
  jupyterlab_requirements/cli.py
  jupyterlab_requirements/dependency_management/__init__.py
  jupyterlab_requirements/dependency_management/lib.py
  jupyterlab_requirements/dependency_management/magic_commands.py
Labels: approved, size/S

#563 Add force flag for set-kernel command
  docs/source/horus-cli.md
  docs/source/horus-magic-commands.md
  jupyterlab_requirements/cli.py
  jupyterlab_requirements/dependency_management/lib.py
  jupyterlab_requirements/dependency_management/magic_commands.py
Labels: approved, size/M

#567 Extend requirements handling
  Pipfile
  Pipfile.lock
  jupyterlab_requirements/dependency_management/lib.py
  package.json
  requirements.txt
  src/helpers.ts
  src/notebook.ts
  src/types/requirements.ts
  style/index.css
Labels: approved, size/XL

#569 Add kernel specific commands
  docs/source/horus-cli.md
  docs/source/horus-magic-commands.md
  jupyterlab_requirements/cli.py
  jupyterlab_requirements/dependency_management/__init__.py
  jupyterlab_requirements/dependency_management/kernel_handler.py
  jupyterlab_requirements/dependency_management/lib.py
  jupyterlab_requirements/dependency_management/magic_commands.py
Labels: approved, size/L

#570 Add adviser report output to horus magic commands
  jupyterlab_requirements/dependency_management/lib.py
  jupyterlab_requirements/dependency_management/magic_commands.py
  src/index.ts
Labels: approved, size/L

#574 Add output results to cli
  jupyterlab_requirements/cli.py
  jupyterlab_requirements/dependency_management/__init__.py
  jupyterlab_requirements/dependency_management/lib.py
  jupyterlab_requirements/dependency_management/magic_commands.py
Labels: approved, size/S

#577 Add link to v0.13.0 video
  README.rst
Labels: approved, size/XS

#580 Update the labels for the bug and feature templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, size/XS

#575 Extend horus discover command using new user-API endpoint
  .prow.yaml
  Pipfile
  Pipfile.lock
  docs/source/horus-magic-commands.md
  jupyterlab_requirements/cli.py
  jupyterlab_requirements/dependency_management/__init__.py
  jupyterlab_requirements/dependency_management/lib.py
  jupyterlab_requirements/dependency_management/magic_commands.py
  jupyterlab_requirements/dependency_management/thoth_invectio.py
  package.json
  requirements.txt
  src/components/dependencyManagementUI.tsx
  src/helpers.ts
  src/index.ts
Labels: approved, size/XL

#578 Add Thoth analysis ID to metadata (if thoth is used, remove if pipenv is used) and standardize print reports methods
  jupyterlab_requirements/cli.py
  jupyterlab_requirements/dependency_management/dependencies_files_handler.py
  jupyterlab_requirements/dependency_management/jupyterlab_requirements.yaml
  jupyterlab_requirements/dependency_management/lib.py
  jupyterlab_requirements/dependency_management/magic_commands.py
  jupyterlab_requirements/dependency_management/thoth.py
  src/components/KernelHandlerDialog.tsx
  src/components/dependencyManagementUI.tsx
  src/dependencyManagementButton.ts
  src/helpers.ts
  src/index.ts
  src/kernel.ts
  src/notebook.ts
  src/thoth.ts
  src/types/thoth.ts
Labels: approved, size/XL

#582 Add note in docs
  docs/source/horus-cli.md
  docs/source/horus-magic-commands.md
  docs/source/jupyterlab-requirements-ui.md
Labels: approved, size/XS
