Repository thoth-station/jupyterlab-requirements, pull requests merged in 2022-01, with the labels that each got.

#597 Adjust UI inputs and make resolution engine option
  jupyterlab_requirements/dependency_management/base.py
  jupyterlab_requirements/dependency_management/install_handler.py
  jupyterlab_requirements/dependency_management/pipenv.py
  jupyterlab_requirements/dependency_management/thoth.py
  src/components/dependencyManagementUI.tsx
  src/types/requirements.ts
  src/types/thoth.ts
  style/index.css
Labels: approved, size/L

#598 Update readme for development
  README.rst
Labels: approved, size/XS

#601 fixed onChange functions
  src/components/dependencyManagementUI.tsx
Labels: approved, size/M

#602 Add hardware part of thoth config in types
  Pipfile
  Pipfile.lock
  src/components/dependencyManagementUI.tsx
  src/types/thoth.ts
Labels: approved, size/L

#606 Fix version in package.json
  package.json
Labels: approved, size/XS
