Repository thoth-station/jupyterlab-requirements, pull requests merged in 2022-08, with the labels that each got.

#637 Use the pyproject.toml for mypy conf and pre-commit for mypy run
  .pre-commit-config.yaml
  .prow.yaml
  mypy.ini
  pyproject.toml
Labels: approved, size/M

#636 fixed api bugs
  src/components/dependencyManagementConstraintPicker.tsx
  src/components/dependencyManagementUI.tsx
  src/types/thoth.ts
Labels: approved, size/L, lgtm

#638 Fixed argparse
  jupyterlab_requirements/dependency_management/magic_commands.py
Labels: approved, size/S
