Repository thoth-station/jupyterlab-requirements, pull requests merged in 2022-02, with the labels that each got.

#603 update-maintainers
  .thoth.yaml
  OWNERS
Labels: approved, size/XS

#610 Update the pre-commit hooks
  .pre-commit-config.yaml
Labels: approved, size/S

#608 Added dropdown menus
  .prow.yaml
  package.json
  src/components/OutsideAlerter.tsx
  src/components/dependencyManagementAutocomplete.tsx
  src/components/dependencyManagementConstraintPicker.tsx
  src/components/dependencyManagementTableRowNew.tsx
  src/icons.ts
  style/icons/info.svg
  style/index.css
Labels: approved, size/XL

#612 Fix UI issue and relock logic once package is deleted
  src/components/dependencyManagementUI.tsx
Labels: approved, size/XS

#619 Remove codeowners
  .github/CODEOWNERS
Labels: approved, size/XS

#618 Update jupyterlab-requirements-ui.md
  docs/source/jupyterlab-requirements-ui.md
Labels: approved, size/S

#623 added warning banners
  src/components/StylizedBanner.tsx
  src/components/dependencyManagementUI.tsx
  style/index.css
Labels: approved, size/L
